### ISSUE TITLE
SB3 version

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [mjlbach/iGibson-baselines#1]
Hi Michael,

I saw your post on Ray forums ("Issues reproducing stable-baselines3 PPO performance with rllib") and I was wondering if you had your code for iGibson trained using stable-baselines3 PPO somewhere I could look at?

I've been using DAgger on iGibson and I wanted to see if there were any specific examples with SB3 PPO on iGibson.

Kevin

**Comment by mjlbach** [comment]
Yes!

We just released iG 2.0 which includes the following scripts depending on if you want to use the BEHAVIOR avatar or turtlebot, note this is for point nav which is the only thing we've managed to get PPO to do reliably.

https://github.com/StanfordVL/iGibson/blob/master/igibson/examples/demo/stable_baselines3_behavior_example.py
https://github.com/StanfordVL/iGibson/blob/master/igibson/examples/demo/stable_baselines3_example.py

I also had this dockerized example from the ray post:

https://github.com/mjlbach/iGibson-ray-repro/blob/master/trainers/stable-baselines3_example.py

**Comment by kevin-thankyou-lin** [comment]
This is brilliant - thank you for the additional info, too!

**Comment by mjlbach** [comment]
No problem, feel free to reach out if you have any success or questions (especially with Ray, as I have not been able to reproduce our SB3 results)
